name: Testes Works 1

on: workflow_dispatch

jobs:
    ler_readme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Ler README file
              run: cat README.md